{
 "title": "FiwareController",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index  AS \"time\",\n  entity_id AS metric,\n  temperature\nFROM etweatherstation\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "HeaterPower",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  heaterpower_info AS \"heaterpower_info\"\nFROM etheater\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  temperature\nFROM ettemperaturesensor \nORDER BY 1,2"
    }
   ]
  }
 ]
}