version: '3.8'
services:
  Controller:
    container_name: pid4fiware
    hostname: pid4fiware
    image: pid4fiware  # keep the same with your local image name
    restart: always
    volumes:
      # bind mount the secret on the local file. The secret has to be updated in the local file
      - ./keycloak_token_handler/.env:/app/keycloak_token_handler/.env
      - ./PID4FIWARE.py:/app/PID4FIWARE.py
    environment:
      # Fiware platform information
      - CB_URL=http://cb.n5geh.de  # host.docker.internal in the container maps up with the localhost
      - FIWARE_SERVICE=n5gehdemo
      - FIWARE_SERVICE_PATH=/
      # Controller entity id
      - CONTROLLER_NAME=PID_example
      # Sensor information
      - SENSOR_ENTITY_NAME=urn:ngsi-ld:TemperatureSensor:003
      - SENSOR_TYPE=TemperatureSensor
      - SENSOR_ATTR=temperature
      # Actuator information
      - ACTUATOR_ENTITY_NAME=urn:ngsi-ld:Heater:001
      - ACTUATOR_TYPE=Heater
      - ACTUATOR_COMMAND=heater_power
      # Controller parameters
      - SETPOINT=20  # set point of the process variable
      - PAUSE_TIME=0.5  # sampling time step
      - LIM_LOW=0  # lower limit of the actuator
      - LIM_UPPER=10000  # upper limit of the actuator
      # Tuning parameters, use negative values for reverse mode
      - KP=200  # The value for the proportional gain Kp
      - KI=50  # The value for the integral gain Ki
      - KD=0  # The value for the derivative gain Kd
      # Security settings
      - SECURITY_MODE=False  # set to True if activate security mode
    networks:
        - pid_control
  Panel:
    container_name: pidpanel
    hostname: pidpanel
    image: pidpanel  # keep the same with your local image name
    restart: always
#    volumes:
#      - ./control_panel/ControllerPanel.py:/app/ControllerPanel.py
    ports:
      - "80:80"  # use other port, e.g. "3000:80", if port 80 is already allocated
    environment:
      # Fiware platform information
      - CB_URL=http://cb.n5geh.de  # host.docker.internal in the container maps up with the localhost
      - FIWARE_SERVICE=n5gehdemo
      - FIWARE_SERVICE_PATH=/
    networks:
      - pid_control
networks:
   pid_control:        
