version: '3.8'
services:
  Panel:
    container_name: pidpanel
    hostname: pidpanel
    image: pidpanel  # keep the same with your local image name
    restart: always
    volumes:
      - ./ControllerPanel.py:/app/ControllerPanel.py
    ports:
      - "80:80"  # use other port, e.g. "3000:80", if port 80 is already allocated
    environment:
      # Fiware platform information
      - CB_URL=http://host.docker.internal:1026  # host.docker.internal in the container maps up with the localhost
      - FIWARE_SERVICE=controller
      - FIWARE_SERVICE_PATH=/
    networks:
      - pid_control
networks:
   pid_control:        
